select *
from EMPLOYEES;
-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE
select COUNTRY_NAME, REGION_NAME
from COUNTRIES c inner join REGIONS r on c.REGION_ID = r.REGION_ID;

-- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
select FIRST_NAME, JOB_TITLE
from EMPLOYEES e inner join JOBS j on e.JOB_ID = j.JOB_ID;

-- 3. FIND OUT DEPARTMENT_NAME AND CITY
select DEPARTMENT_NAME, CITY
from DEPARTMENTS d inner join LOCATIONS l on d.LOCATION_ID = l.LOCATION_ID;

-- 4. FIND OUT ALL CITIES  AND COUNTRY NAMES
SELECT CITY, COUNTRY_NAME
from LOCATIONS l right join COUNTRIES c on l.COUNTRY_ID = c.COUNTRY_ID;

-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME  FOR DEPARTMENT ID 80 OR 40
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, e.DEPARTMENT_ID
from EMPLOYEES e left join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE d.DEPARTMENT_ID in (40, 80);

-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
select CITY, COUNTRY_NAME, REGION_NAME
from LOCATIONS l right join COUNTRIES c on l.COUNTRY_ID = c.COUNTRY_ID
inner join REGIONS r on c.REGION_ID = r.REGION_ID;

-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
select FIRST_NAME, JOB_TITLE, DEPARTMENT_NAME, CITY
from EMPLOYEES e inner join JOBS j on e.JOB_ID = j.JOB_ID
inner join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
inner join LOCATIONS L on d.LOCATION_ID = L.LOCATION_ID;

-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME
SELECT FIRST_NAME, JOB_TITLE, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME
from EMPLOYEES e inner join JOBS j on e.JOB_ID = j.JOB_ID
left join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
left join LOCATIONS l on d.LOCATION_ID = l.LOCATION_ID
left join COUNTRIES c on l.COUNTRY_ID = c.COUNTRY_ID
left join REGIONS r on c.REGION_ID = r.REGION_ID;


--9. FIND OUR  EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS
--  INCLUDING  WHERE DO NOT HAVE ANY EMPLOYEE.
SELECT FIRST_NAME, LAST_NAME, e.DEPARTMENT_ID, DEPARTMENT_NAME
from EMPLOYEES e right join DEPARTMENTS D on e.DEPARTMENT_ID = d.DEPARTMENT_ID;

--10. FIND OUT ALL DEPARTMENT_NAME  , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS  WITH NO DEPARTMENT
select DEPARTMENT_NAME, l.LOCATION_ID, COUNTRY_ID
from DEPARTMENTS d right join LOCATIONS l on d.LOCATION_ID = l.LOCATION_ID;

--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT
select DEPARTMENT_NAME, l.LOCATION_ID, COUNTRY_NAME
from DEPARTMENTS d right join LOCATIONS l on d.LOCATION_ID = l.LOCATION_ID
right join COUNTRIES c on l.COUNTRY_ID = c.COUNTRY_ID;

--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME
-- INCLUDING THOSE DOES NOT HAVE DEPARTMENT
-- INCLUDING THOSE DEPARTMENTS  DOES NOT HAVE ANY MATCHING EMPLOYEES
select FIRST_NAME, d.DEPARTMENT_ID, DEPARTMENT_NAME
from EMPLOYEES e full outer join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID;